// import Input from '@/components/Input/Input.tsx'
import Input from '@/components/Input/Input'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* {children} */}
        <div className="p-3 flex justify-center">
          <Input intent="primary" errorMessage="Error de prueba" />
        </div>
      </body>
    </html>
  )
}
